### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by MehdiZare** [timkpaine/tdameritrade#11]
`tdameritrade.auth.authentication`
can't be executed, error message:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: module 'tdameritrade' has no attribute 'auth'

**Comment by hking1122** [comment]
I got the same issue. 
AttributeError: module 'tdameritrade' has no attribute 'auth'

**Comment by timkpaine** [comment]
have you tried `import tdameritrade.auth`?

**Comment by hking1122** [comment]
I didn't.  I tried import tdameritrade.auth. it works. but i didn't get the login page. i got a error page. it shows "This may be due to a technical error, or the client application may be an attempt to fraudulently access your account. If you believe you’ve received this message in error, please contact the publisher of the client application. For more information on securing your account, please see our security page."
maybe authentication is closed.

**Comment by timkpaine** [comment]
You need to make sure to type things in exactly as they are set up for your account, including things like the redirect url. [This thread](https://github.com/timkpaine/tdameritrade/issues/4) has a few people's experiences and tips.

**Comment by hking1122** [comment]
Yes. I input wrong redirect url. It’s working, I got the login page. Thanks!
