### ISSUE TITLE
first time login

### ISSUE THREAD

**Issue by shahab-cl** [timkpaine/tdameritrade#137]
**Describe the bug**
On step 7 of https://tdameritrade.readthedocs.io/en/latest/index.html.  it dosent mention how to get the client_id.  Also where are both tokens used.  I only see the refresh_token being passed to TDClient.

It would be nice so that tdameritrade.auth.authentication could be run from the python file.
i.e.
If refresh token not found, then run tdameritrade.auth.authentication and save the data into a json file for future use.

**Comment by timkpaine** [comment]
https://developer.tdameritrade.com/content/getting-started

You can run `tdameritrade.auth.authentication` from a python file. Do you mean purely from python without a browser?

**Comment by alelasantillan** [comment]
Instead of using a python file, type **python** in the terminal and run this in the prompt:
>>> import tdameritrade
>>>tdameritrade.auth.authentication(redirect_uri='http://localhost',client_id='LSKJFSALKFSLFSLDKFSDAD') 
**note: in redirect_uri put the same address you put in developer.tdameritrade.com when registering your app**
Then you will be prompted with:
**after giving access, hit enter to continue**
and a browser window should open the auth form. Put the username and password of your td acct (not the developer's) and press continue, enter the code sent to your phone and press continue.
Then press enter in the terminal and voila:
your access_token, refresh_token and more info appear into the terminal.

**Comment by JimCollinsDC** [comment]
The above works. I use venv
pip install pandas
pip install requests
pip install selenium
then:
>>>tdameritrade.auth.authentication(redirect_uri='http://localhost',client_id='LSKJFSALKFSLFSLDKFSDAD')
